c Version 1.6 --- updated to CODATA 1998 values 20020213 WH
c----------------------------------------------------------------------
c Physical constants (in cgs/electromagnetic units)
c    ge:     free-electron g-value
c    betae:  Bohr magneton
c    hbar:   Planck's constant
c    gammae: electronic gyromagnetic ratio
c    kb:     Boltzmann's constant
c----------------------------------------------------------------------
        DOUBLE PRECISION GE,BETAE,GAMMAE,HBAR,KB
        PARAMETER( GE=2.002 319 304 3737 D0,
     #             BETAE=927.400 899 D-23,
     #             HBAR=1.054 571 596 D-27,
     #             GAMMAE=1.760 859 794 D7,
     #             KB=1.380 6503 D-16)
