c Version 1.6 8/12/94
c*********************************************************************
c
c       declarations of array dimensioning parameters for EPRLL
c
c*********************************************************************
c
        integer MXSTEP,MXDIM,MXDIM1,MXEL,MXCALC,MXPT,MXORT
	parameter (MXSTEP=2000,MXDIM=30000,MXDIM1=MXDIM+1,MXEL=3000000,
     #             MXCALC=30,MXPT=512,MXORT=100)
c
c*********************************************************************
c

