c Version 1.6 8/12/94
c----------------------------------------------------------------------
c                    =========================
c                      common block TIMER
c                    =========================
c Variables and definitions for timing different parts of a 
c slow-motional calculation using the dtime function
c----------------------------------------------------------------------
      real tarray,dtime
      common /timer/tarray(3)
c      external dtime







