c Version 1.6 8/12/94
c**********************************************************************
c                  =========================
c                   include file VERSION
c                  =========================
c    Contains version information. Because of data statements, this
c    may need to be the last "include" file for some compilers
c----------------------------------------------------------------------
c
      character version*4,vdate*8
      data version / '1.6b' /
      data vdate / '2-Sep-97' /
